### ISSUE TITLE
Replace hardcoded path for autostart with Used Details from Build Process

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#114]
Following our changes in how PersonalAnalytics is signed and deployed, we need to make sure the autostart after the computer is restarted still works (due to a hardcoded path).

Specifically, check for different culture/languages (as the path contains an Umlaut: "Universität Zürich").

**Comment by s-mueller** [comment]
Probably for the same reason, uninstalling the app also does not work anymore. I can find the path /AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Universität Zürich

**Comment by s-mueller** [comment]
Can't reproduce on dev branch, but on master and biometrics

**Comment by s-mueller** [comment]
The problem is solved for now, but in future it might be worth to replace the hardcoded path with the publisher parameter set during the build process.

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
