### ISSUE TITLE
Unify Visualizations of similar data

### ISSUE THREAD

**Issue by s-mueller** [HASEL-UZH/PersonalAnalytics#116]
Think of a clever way to visualize similar data from multiple sources (e.g. HR from Polar, Garmin and Fitbit)

**Comment by casaout** [comment]
Maybe create a "shared" visualization that can be re-used in all trackers (to avoid code duplication)

**Comment by casaout** [comment]
related to #167

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
