### ISSUE TITLE
Refactor Taskbar NotfiyIcon

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#132]
We are currently using two versions of the NofiyIcon:
- In PolarTracker: the WindowsForms-version
- In PersonalAnalytics: the Hardcodet.Wpf.

I think we should unify that (at some point). Also a notification from the PolarTracker creates a new icon in the taskbar, instead of using the original one.

What's the best way to do refactor this? And, is there a way to create different callback-functions for the different notifications (balloon-tips) ?

**Comment by s-mueller** [comment]
What do you mean by: "creates a new icon in the taskbar instead of using the original one"?

**Comment by casaout** [comment]
> What do you mean by: "creates a new icon in the taskbar instead of using the original one"?
It creates a second icon (with a yellow exclamation mark) and doesn't (temporarily) replace the PA-icon (as other applications do) as it creates a second instance.

(I don't think this refactoring is urgent, but I wanted to write it down and think about it later)

**Comment by s-mueller** [comment]
Ok, got it.

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
