### ISSUE TITLE
Improve how Updates are handled

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#14]
- [ ] Not forced updates should show a Toast Notification instead of a MessageBox (Problem here is to handle multiple click events of BalloonTips: http://stackoverflow.com/questions/34956678/handling-click-events-of-multiple-taskbaricon-showballoontips)
- [ ] Forced Updates should (maybe) just be installed
- [ ] check for updates in settings/menu?

**Comment by tzimmermsr** [comment]
Maybe a "Check for updates" menu item

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
