### ISSUE TITLE
Pomodoro Issues

### ISSUE THREAD

**Issue by ghost** [HASEL-UZH/PersonalAnalytics#175]
- [ ] support refreshing the Retrospection: save currently running Pomodoro and resume it. (now it is lost but FlowLight remains busy)
- [ ] add timeline visualization of daily pomodoros
- [ ] add weekly visualization of pomodoros
- [ ] integrate with GoalSetting? --> e.g. set number of weekly Pomodoros.
- [ ] add timer for breaks too (short and long breaks)
- [ ] add settings to change the pomodoro and break durations, and the number of iterations before the long break
- [ ] add a setting to synch / unsynch the Pomodoro timer with the FlowLight
- [x] add a visual cue about the remaining duration of the pomodoro (e.g. progressbar or color)
- [ ] add the visual cue in FlowLight. E.g. red during first 20 min, purple in last 5 min, blinking purple in last 15s
- [ ] add audio cues when the pomodoro is over and almost over
- [ ] add a notification when the pomodoro is over (use system notifications and at the same time clean it up and put it in Shared (already used twice, in Polar Tracker and reminder when PA is paused)
- [ ] rethink FlowLight integration? Now the light is set to Busy during a Pomodoro, but this can be overwritten by the user via Skype or the context menu.

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
