### ISSUE TITLE
Add productivity tracker pop-up

### ISSUE THREAD

**Issue by csatterfield** [HASEL-UZH/PersonalAnalytics#213]
Should use 7-point scale as in Windows version, try to make it look as similar as possible. Separate existing productivity tracker functionality from Task tracker.

**Comment by casaout** [comment]
In the windows-version, it's called "UserEfficiencyTracker". Not optimal since at the moment it only asks for "productivity", but the first iterations included several questions.

Please note that the pop-up has an interval (e.g. every 30/60/120 minutes) and day (once a day) component.
