### ISSUE TITLE
Extend list of applications categorized by activity tracker

### ISSUE THREAD

**Issue by csatterfield** [HASEL-UZH/PersonalAnalytics#214]

**Comment by casaout** [comment]
it might make sense to create a JSON/XML file for the mapping and reading from it in the Mac and Windows clients?

**Comment by casaout** [comment]
Chris, @RaphaelRo and I started working on extracting the ApplicationToActivityMapper to a separate project, so we can more easily re-use it elsewhere.

Please make your list-updates there: https://github.com/sealuzh/ApplicationToActivityMapper
Also, my comment about using JSON/XML for the mapping list was described here: https://github.com/sealuzh/ApplicationToActivityMapper/issues/1

Let's keep this issue open, until you extended the list with your applications (especially targeted to MacOs).

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
