### ISSUE TITLE
ActiveApplicationTracker - tracking of active file

### ISSUE THREAD

**Issue by scholtzan** [HASEL-UZH/PersonalAnalytics#235]
Using [representedURL](https://developer.apple.com/documentation/appkit/nswindow/1419066-representedurl) we might be able to get the file path of the file opened in some window. Collecting this information might be quite useful.

**Comment by casaout** [comment]
Absolutely! Do you know if this is something specific to applications or does the representedURL always know the file-path the app was opened from (or similar)?


From parsing the window titles, we (usually) know the file-names (but not paths), so this could be much more extensive & accurate.

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
