### ISSUE TITLE
AppleWatch support

### ISSUE THREAD

**Issue by anaderi** [HASEL-UZH/PersonalAnalytics#257]
Superb project! Are there any plans to add AppleWatch support?

**Comment by casaout** [comment]
that's an interesting idea! What exactly would you be interested to have on your AppleWatch?

See visualizations from your computer monitoring? 
Or share AppleWatch data (similar to Fitbit and Polar)?

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
