### ISSUE TITLE
Study Specific Setup

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#273]
Tasks:
- [x] Study-Specific config
- [x] Unique automatically-generated subject ID
- [ ] `P2` study Specific Builds

### Study-Specific Config
What we currently want to make study-specific, maybe in a code- or text-based (dynamic) config-file is:
- experience sampling question `string`
- experience sampling response options  `list/array` [response-Likert1, response-Likert4, response-Likert7]
- experience sampling interval `integer` (in minutes)
- experience sampling randomization `bool`  (`tbd` or min/max randomization interval)
- study name `string`
- study short description `string`
- study info url `string/url`
- study privacy policy url `string/url`
- study upload url `string/url`
- study contact name `string`
- study contact email `string/email`
- isUserInputTrackerEnabled `bool`
- isWindowActivityTrackerEnabled `bool`
- isExperienceSamplingEnabled `bool`

### Unique Subject ID
- When installing the tool, a unique subject ID should be created (ideally combination of 6 random letters/numbers); so people could also type it in manually 
- Persist the subject ID (and study name) in the database
- That subject ID is also shown in the about page #272
- `P2` When storing the subject ID, is there a simple/easy way to make it readonly (even if defeats the purpose a bit), maybe using [triggers](https://stackoverflow.com/questions/12911947/read-only-fields-in-sqlite3-database-table)? `tbd`

### Study Specific Builds
`tbd` To be further discussed: how do we best create study-specific builds? - one idea could be to just create a fork/branch and adjust the GH action file (and where necessary code).

**Comment by casaout** [comment]
@SRichner Thanks, looks great!  I am currently discussing the feedbacks with Malte and will come back to you.
A few minor thoughts so far:
- Please rename userIdLength to subjectIdLength (generally using `subjectId` would be better IMO)
- regarding the `responseOptions`, we are thinking of wanting to use LIkert-Scale option. what is not super clear yet if we should fix them to 7-point LIkert Scale, or if some setups require others. How time-consuming will it be to make it more dynamic (say between 3-7 response options)?
- Another thing Malte is currently thinking about is setting a list of questions and randomly picking one

**Comment by casaout** [comment]
@SRichner 

Few updates:
- please change it to be able to have multiple questions (1-n) and add a setting `IsRandomized`. If true, it randomly picks one, if not, it uses the given order
- The timing ist still `tbd`

thank you!

**Comment by SRichner** [comment]
@casaout 
Sorry, just saw this. So should the app keep track of the order in the database as well? Or just while it's running?

**Comment by casaout** [comment]
> @casaout Sorry, just saw this. So should the app keep track of the order in the database as well? Or just while it's running?

you mean the order in which questions were asked? isn't this given by the timestamp of storing responses (and storing "skip" in case it was skipped/not responded)?

**Comment by SRichner** [comment]
> you mean the order in which questions were asked? isn't this given by the timestamp of storing responses (and storing "skip" in case it was skipped/not responded)?
let's discuss this on Thursday
