### ISSUE TITLE
PersonalAnalytics for Mac

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#3]
Many users from various previous studies wished a version for the Mac OS.

Evaluate if:
- [ ] Microsoft's new [Visual Studio Code](https://www.visualstudio.com/en-us/products/code-vs.aspx) and the [.NET Core](https://github.com/dotnet/corefx) for Mac OS could make it work?
- [ ] Or [Mono](http://www.mono-project.com/docs/about-mono/supported-platforms/osx/)?
- [ ] Or [Electron](http://electron.atom.io)? (cross-platform desktop apps with JavaScript)

Hint: The visualizations are likely no problem (as they are already implemented in JavaScript/HTML/CSS); but some trackers are (WindowActivityTracker, UserInputTracker) as they require native hooks into the OS.

**Comment by tomFr** [comment]
We should chat with Gail about it. Her student Jonathan is working on a tracker for MacOS.

**Comment by casaout** [comment]
Update: @csatterfield is interested in publicly maintaining his Mac-port. Will work on it with me in September 2018.

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics. A macOS Version is now available.
