### ISSUE TITLE
Check Dark/Light-Mode of UI

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#306]
- [x] is the experience sampling also available in dark mode? (created separate issue #308)
- [x] let's briefly check all windows in light mode
- [x] on Malte's computer, the onboarding window on the second page looked off
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/5212692/b7daff04-47c9-4226-86b7-1fb4e6c490f6)

- [x] On Windows, the titles in the onboarding, about and export screens are a bit too light-gray:
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/5212692/5f499e29-30a6-427d-8994-dd9346087667)

- [x] in light mode, the bullets of pagination are a bit off:
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/5212692/ee188389-bc00-4ffe-992d-c27e7057f37d)

**Comment by SRichner** [comment]
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/14821076/cd2421d0-1190-4e48-a4f3-a75f275e40d0)
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/14821076/295a0fa6-7402-49dc-a50a-a04aa6e4adef)
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/14821076/6b3ee337-c27c-4207-b8bb-92bd6272ec36)
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/14821076/5abd1907-33cd-4042-83fb-dcaa97c9178a)
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/14821076/ef5e406b-944e-4b83-a24f-e05219f62625)
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/14821076/77de98e2-8b4d-4ffa-af47-e883f810d3d4)
![Image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/14821076/65a297e6-8503-4342-bdb5-363d237ca5e4)
